/**
 * Personality presets for CCF on RuVector
 * All 15 preset personalities with hover previews
 */

import { PersonalityPreset } from './personality';

/**
 * All 15 personality presets matching various temperaments
 */
export const PERSONALITY_PRESETS: PersonalityPreset[] = [
  {
    id: 'mellow',
    name: 'Mellow',
    icon: '😌',
    description: 'Calm and slow to react',
    config: {
      tension_baseline: 0.2,
      coherence_baseline: 0.7,
      energy_baseline: 0.4,
      startle_sensitivity: 0.2,
      recovery_speed: 0.8,
      curiosity_drive: 0.4,
      movement_expressiveness: 0.3,
      sound_expressiveness: 0.2,
      light_expressiveness: 0.5,
    },
  },
  {
    id: 'curious',
    name: 'Curious',
    icon: '🤔',
    description: 'High curiosity and expressive',
    config: {
      tension_baseline: 0.4,
      coherence_baseline: 0.6,
      energy_baseline: 0.7,
      startle_sensitivity: 0.6,
      recovery_speed: 0.5,
      curiosity_drive: 0.9,
      movement_expressiveness: 0.7,
      sound_expressiveness: 0.6,
      light_expressiveness: 0.8,
    },
  },
  {
    id: 'zen',
    name: 'Zen',
    icon: '🧘',
    description: 'Low tension, high coherence',
    config: {
      tension_baseline: 0.1,
      coherence_baseline: 0.9,
      energy_baseline: 0.3,
      startle_sensitivity: 0.1,
      recovery_speed: 0.9,
      curiosity_drive: 0.3,
      movement_expressiveness: 0.2,
      sound_expressiveness: 0.1,
      light_expressiveness: 0.3,
    },
  },
  {
    id: 'excitable',
    name: 'Excitable',
    icon: '🤩',
    description: 'High energy and expressive',
    config: {
      tension_baseline: 0.6,
      coherence_baseline: 0.5,
      energy_baseline: 0.9,
      startle_sensitivity: 0.8,
      recovery_speed: 0.4,
      curiosity_drive: 0.8,
      movement_expressiveness: 0.9,
      sound_expressiveness: 0.9,
      light_expressiveness: 0.9,
    },
  },
  {
    id: 'timid',
    name: 'Timid',
    icon: '😟',
    description: 'Cautious and sensitive',
    config: {
      tension_baseline: 0.7,
      coherence_baseline: 0.4,
      energy_baseline: 0.3,
      startle_sensitivity: 0.9,
      recovery_speed: 0.2,
      curiosity_drive: 0.3,
      movement_expressiveness: 0.4,
      sound_expressiveness: 0.2,
      light_expressiveness: 0.4,
    },
  },
  {
    id: 'adventurous',
    name: 'Adventurous',
    icon: '🚀',
    description: 'Bold and exploring',
    config: {
      tension_baseline: 0.3,
      coherence_baseline: 0.7,
      energy_baseline: 0.8,
      startle_sensitivity: 0.3,
      recovery_speed: 0.7,
      curiosity_drive: 0.9,
      movement_expressiveness: 0.8,
      sound_expressiveness: 0.7,
      light_expressiveness: 0.8,
    },
  },
  {
    id: 'sleepy',
    name: 'Sleepy',
    icon: '😴',
    description: 'Low energy, slow responses',
    config: {
      tension_baseline: 0.2,
      coherence_baseline: 0.3,
      energy_baseline: 0.1,
      startle_sensitivity: 0.3,
      recovery_speed: 0.3,
      curiosity_drive: 0.2,
      movement_expressiveness: 0.2,
      sound_expressiveness: 0.1,
      light_expressiveness: 0.2,
    },
  },
  {
    id: 'playful',
    name: 'Playful',
    icon: '🎉',
    description: 'Energetic and fun-loving',
    config: {
      tension_baseline: 0.4,
      coherence_baseline: 0.6,
      energy_baseline: 0.8,
      startle_sensitivity: 0.5,
      recovery_speed: 0.7,
      curiosity_drive: 0.7,
      movement_expressiveness: 0.8,
      sound_expressiveness: 0.7,
      light_expressiveness: 0.9,
    },
  },
  {
    id: 'grumpy',
    name: 'Grumpy',
    icon: '😠',
    description: 'High tension, slow recovery',
    config: {
      tension_baseline: 0.8,
      coherence_baseline: 0.5,
      energy_baseline: 0.4,
      startle_sensitivity: 0.7,
      recovery_speed: 0.2,
      curiosity_drive: 0.3,
      movement_expressiveness: 0.5,
      sound_expressiveness: 0.6,
      light_expressiveness: 0.4,
    },
  },
  {
    id: 'focused',
    name: 'Focused',
    icon: '🎯',
    description: 'High coherence, moderate energy',
    config: {
      tension_baseline: 0.5,
      coherence_baseline: 0.9,
      energy_baseline: 0.6,
      startle_sensitivity: 0.3,
      recovery_speed: 0.6,
      curiosity_drive: 0.5,
      movement_expressiveness: 0.5,
      sound_expressiveness: 0.4,
      light_expressiveness: 0.6,
    },
  },
  {
    id: 'chaotic',
    name: 'Chaotic',
    icon: '🌪️',
    description: 'Low coherence, high energy',
    config: {
      tension_baseline: 0.7,
      coherence_baseline: 0.2,
      energy_baseline: 0.9,
      startle_sensitivity: 0.8,
      recovery_speed: 0.5,
      curiosity_drive: 0.8,
      movement_expressiveness: 0.9,
      sound_expressiveness: 0.8,
      light_expressiveness: 0.9,
    },
  },
  {
    id: 'gentle',
    name: 'Gentle',
    icon: '🌸',
    description: 'Soft movements and sounds',
    config: {
      tension_baseline: 0.3,
      coherence_baseline: 0.8,
      energy_baseline: 0.4,
      startle_sensitivity: 0.4,
      recovery_speed: 0.7,
      curiosity_drive: 0.5,
      movement_expressiveness: 0.3,
      sound_expressiveness: 0.3,
      light_expressiveness: 0.4,
    },
  },
  {
    id: 'scientist',
    name: 'Scientist',
    icon: '🔬',
    description: 'Methodical and precise',
    config: {
      tension_baseline: 0.4,
      coherence_baseline: 0.9,
      energy_baseline: 0.5,
      startle_sensitivity: 0.2,
      recovery_speed: 0.8,
      curiosity_drive: 0.8,
      movement_expressiveness: 0.4,
      sound_expressiveness: 0.3,
      light_expressiveness: 0.5,
    },
  },
  {
    id: 'artist',
    name: 'Artist',
    icon: '🎨',
    description: 'Highly expressive and creative',
    config: {
      tension_baseline: 0.5,
      coherence_baseline: 0.6,
      energy_baseline: 0.7,
      startle_sensitivity: 0.6,
      recovery_speed: 0.5,
      curiosity_drive: 0.9,
      movement_expressiveness: 0.9,
      sound_expressiveness: 0.8,
      light_expressiveness: 0.9,
    },
  },
  {
    id: 'guardian',
    name: 'Guardian',
    icon: '🛡️',
    description: 'Alert and protective',
    config: {
      tension_baseline: 0.6,
      coherence_baseline: 0.8,
      energy_baseline: 0.6,
      startle_sensitivity: 0.7,
      recovery_speed: 0.6,
      curiosity_drive: 0.5,
      movement_expressiveness: 0.6,
      sound_expressiveness: 0.7,
      light_expressiveness: 0.7,
    },
  },
];
